### ISSUE TITLE
Images don't work on mobile

### ISSUE THREAD

**Issue by nicholasalanbrown** [samcorcos/meteor-react-ionic-tinder-3#1]
Terrific repo/post series. The images show up fine in my browser, but they show as broken image links on both iPhone and Android. Any idea what's happening?

**Comment by samcorcos** [comment]
Hmm... No idea why that would be. The images are just urls not static
images. Are you on wifi? It might be due to internet speed?

**Comment by nicholasalanbrown** [comment]
Never mind, I solved this by adding `App.accessRule('*')` to my `mobile-config.js` file.

**Comment by samcorcos** [comment]
Interesting! I didn't know that was a thing.
