### ISSUE TITLE
Swipe Animations don't show in iOS Simulator

### ISSUE THREAD

**Issue by thorbenandresen** [samcorcos/meteor-react-ionic-tinder-3#2]
Awesome tutorial Sam! 

The app works fine in the browser, but once I start it with the iOS Simulator the nice swipe left/right transitions don't show. 

iOS Simulator Version 8.4 (SimulatorApp-565.9 )
xCode Version 6.4 (6E35b)

**Comment by samcorcos** [comment]
These should be solved by the optimizations in part 5. If that doesn't do
it, let me know!

**Comment by thorbenandresen** [comment]
Thanks Sam, that worked. I didn't know about part 5, it is not linked to in the previous article on Medium.
